name             's3fs-fuse'
maintainer       'Heavy Water Operations, LLC.'
maintainer_email 'support@hw-ops.com'
license          'Apache-2.0'
description      'Installs/Configures s3fs-fuse'
version          '0.1.4'
depends 'rc_mon'
